runtime: go111
env: flex

manual_scaling:
  instances: 1

#[START env_variables]
env_variables:
  ENV: 'production'
  GO_ENV: 'production'
  APP_HOST: ''
  APP_PORT: '3000'
#[ENV env_variables]

handlers:
- url: /.*
  script: auto
