---
development:
  dialect: postgres
  database: project_k_backend_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: project_k_backend_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: {{envOr "DB_NAME" "project_k_backend"}}
  user: {{envOR "DB_USER" "postgres"}}
  password: {{envOr "DB_PASSWORD" ""}}
  host: {{envOR "DB_HOST" "127.0.0.1"}}
  pool: {{envOR "DB_POOL" "5"}}
