kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-go-stg-env
  namespace: default
data:
  ENV: 'stage'
  DB_HOST: 'localhost'
  DB_PORT: '3306'
  DB_USER: 'postgres'
  DB_NAME: 'project_k_backend_stg'
  DB_POOL: 5
  APP_HOST: ''
  APP_PORT: '3000'
  AUTH_API_HOST: 'auth-go'
  AUTH_API_PORT: '80'
  AUTH_API_PREFIX: ''
