package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/obedtandadjaja/project_k_backend/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Session)
// DB Table: Plural (sessions)
// Resource: Plural (Sessions)
// Path: Plural (/sessions)
// View Template Folder: Plural (/templates/sessions/)

// SessionsResource is the resource for the Session model
type SessionsResource struct{
  buffalo.Resource
}

// List gets all Sessions. This function is mapped to the path
// GET /sessions
func (v SessionsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  sessions := &models.Sessions{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Sessions from the DB
  if err := q.All(sessions); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, sessions))
}

// Show gets the data for one Session. This function is mapped to
// the path GET /sessions/{session_id}
func (v SessionsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Session
  session := &models.Session{}

  // To find the Session the parameter session_id is used.
  if err := tx.Find(session, c.Param("session_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, session))
}

// Create adds a Session to the DB. This function is mapped to the
// path POST /sessions
func (v SessionsResource) Create(c buffalo.Context) error {
  // Allocate an empty Session
  session := &models.Session{}

  // Bind session to the html form elements
  if err := c.Bind(session); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(session)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, session))
  }

  // and redirect to the sessions index page
  return c.Render(201, r.Auto(c, session))
}

// Update changes a Session in the DB. This function is mapped to
// the path PUT /sessions/{session_id}
func (v SessionsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Session
  session := &models.Session{}

  if err := tx.Find(session, c.Param("session_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Session to the html form elements
  if err := c.Bind(session); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(session)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, session))
  }

  // and redirect to the sessions index page
  return c.Render(200, r.Auto(c, session))
}

// Destroy deletes a Session from the DB. This function is mapped
// to the path DELETE /sessions/{session_id}
func (v SessionsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Session
  session := &models.Session{}

  // To find the Session the parameter session_id is used.
  if err := tx.Find(session, c.Param("session_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(session); err != nil {
    return err
  }

  // Redirect to the sessions index page
  return c.Render(200, r.Auto(c, session))
}
