package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/obedtandadjaja/project_k_backend/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (UserPropertyRelationship)
// DB Table: Plural (user_property_relationships)
// Resource: Plural (UserPropertyRelationships)
// Path: Plural (/user_property_relationships)
// View Template Folder: Plural (/templates/user_property_relationships/)

// UserPropertyRelationshipsResource is the resource for the UserPropertyRelationship model
type UserPropertyRelationshipsResource struct{
  buffalo.Resource
}

// List gets all UserPropertyRelationships. This function is mapped to the path
// GET /user_property_relationships
func (v UserPropertyRelationshipsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  userPropertyRelationships := &models.UserPropertyRelationships{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all UserPropertyRelationships from the DB
  if err := q.All(userPropertyRelationships); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(http.StatusOK, r.Auto(c, userPropertyRelationships))
}

// Show gets the data for one UserPropertyRelationship. This function is mapped to
// the path GET /user_property_relationships/{user_property_relationship_id}
func (v UserPropertyRelationshipsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserPropertyRelationship
  userPropertyRelationship := &models.UserPropertyRelationship{}

  // To find the UserPropertyRelationship the parameter user_property_relationship_id is used.
  if err := tx.Find(userPropertyRelationship, c.Param("user_property_relationship_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return c.Render(http.StatusOK, r.Auto(c, userPropertyRelationship))
}

// Create adds a UserPropertyRelationship to the DB. This function is mapped to the
// path POST /user_property_relationships
func (v UserPropertyRelationshipsResource) Create(c buffalo.Context) error {
  // Allocate an empty UserPropertyRelationship
  userPropertyRelationship := &models.UserPropertyRelationship{}

  // Bind userPropertyRelationship to the html form elements
  if err := c.Bind(userPropertyRelationship); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(userPropertyRelationship)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(http.StatusUnprocessableEntity, r.Auto(c, userPropertyRelationship))
  }

  // and redirect to the user_property_relationships index page
  return c.Render(http.StatusCreated, r.Auto(c, userPropertyRelationship))
}

// Update changes a UserPropertyRelationship in the DB. This function is mapped to
// the path PUT /user_property_relationships/{user_property_relationship_id}
func (v UserPropertyRelationshipsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserPropertyRelationship
  userPropertyRelationship := &models.UserPropertyRelationship{}

  if err := tx.Find(userPropertyRelationship, c.Param("user_property_relationship_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind UserPropertyRelationship to the html form elements
  if err := c.Bind(userPropertyRelationship); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(userPropertyRelationship)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(http.StatusUnprocessableEntity, r.Auto(c, userPropertyRelationship))
  }

  // and redirect to the user_property_relationships index page
  return c.Render(http.StatusOK, r.Auto(c, userPropertyRelationship))
}

// Destroy deletes a UserPropertyRelationship from the DB. This function is mapped
// to the path DELETE /user_property_relationships/{user_property_relationship_id}
func (v UserPropertyRelationshipsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserPropertyRelationship
  userPropertyRelationship := &models.UserPropertyRelationship{}

  // To find the UserPropertyRelationship the parameter user_property_relationship_id is used.
  if err := tx.Find(userPropertyRelationship, c.Param("user_property_relationship_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(userPropertyRelationship); err != nil {
    return err
  }

  // Redirect to the user_property_relationships index page
  return c.Render(http.StatusOK, r.Auto(c, userPropertyRelationship))
}
